version: 2

artifacts:
  - name: main
    build:
      type: tier4/universe/main/amd64/v1

simulations:
  - name: lexus_planning_sim
    type: planning_sim_v2
    scenario_parameter_group: common # Necessary to define the name for each vehicle type
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384
      parameters:
        launch_autoware: "true"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe/20230906
        vehicle_model: sample_vehicle
        sensor_model: sample_sensor_kit
        initialize_duration: "90"
  - name: localization
    type: localization
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large
- name: obstacle_segmentation
    type: obstacle_segmentation
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium
  - name: perception
    type: perception
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: gpu1/amd64/large
      pre_tasks:
        - exec: source /home/autoware/autoware.proj/install/setup.bash && ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny model_path:=/home/autoware/autoware_data/lidar_centerpoint model_param_path:=$(ros2 pkg prefix lidar_centerpoint --share)/config/centerpoint_tiny.param.yaml build_only:=true
          mounts:
            - volume: model
      volumes:
        - name: model
          path: /home/autoware/autoware_data/lidar_centerpoint
          preserve_original_files: true        
release:
  components:
    - name: planning
      deployment:
        type: container
        artifact: main
    - name: perception
      deployment:
        type: container
        artifact: main

scenario_parameter_groups:
  # Necessary to update the parameters for each vehicle type
  - name: common
    parameters:
      __ego_center_x__: 1.345
      __ego_center_y__: 0
      __ego_center_z__: 1.25
      __ego_dimensions_width__: 1.896
      __ego_dimensions_length__: 4.89
      __ego_dimensions_height__: 2.5
      wheel_radius: 0.383
      wheel_width: 0.235
      wheel_base: 2.79 # between front wheel center and rear wheel center
      wheel_tread: 1.64 # between left wheel center and right wheel center
      front_overhang: 1.0 # between front wheel center and vehicle front
      rear_overhang: 1.1 # between rear wheel center and vehicle rear
      left_overhang: 0.128 # between left wheel center and vehicle left
      right_overhang: 0.128 # between right wheel center and vehicle right
      max_steer_angle: 0.70 # [rad]
      blind_spot_stop_line_distance: 1.0 # param name in autoware_launch: stop_line_margin
      obstacle_stop_line_distance: 5.0 # param name in autoware_launch: max_longitudinal_margin
      crosswalk_stop_line_distance: 3.5 # param name in autoware_launch: stop_distance_from_crosswalk
      walkway_stop_line_distance: 3.5 # param name in autoware_launch: stop_distance_from_crosswalk
      intersection_stop_line_distance: 3.0 # param name in autoware_launch: stop_line_margin
      traffic_light_stop_line_distance: 0.0 # param name in autoware_launch: stop_margin
